config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_for :users, :path_prefix => 'auth', :skip => [:registrations],
    :controllers => {
        :sessions => "sessions",
    }
    
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      
      devise_for :users, skip: :all
      devise_scope :api_user do
        post '/users/sign_in' => 'sessions#create'
        post '/users/sign_out' => 'sessions#destroy'
        post '/users/sign_up' => 'registrations#create'
      end
      
      get '/users/available_roles' => 'users#available_roles'
      post '/users/update/:id' => 'users#update'
      post '/users/upload_avatar/:id' => 'users#upload_avatar'
      post '/users/change_password/:id' => 'users#change_password'
      post '/users/remove_avatar/:id' => 'users#remove_avatar'
      get '/users/user_info' => 'users#user_info'
            
      get '/posts' => 'posts#index'
      get '/posts/current_user_posts' => 'posts#current_user_posts'
      get '/posts/info' => 'posts#info'
      get '/posts/get_by_location' => 'posts#get_by_location'
      get '/posts/map_posts_listings' => 'posts#map_posts_listings'
      post '/posts/create' => 'posts#create'
      post '/posts/update/:id' => 'posts#update'
      post '/posts/destroy' => 'posts#destroy'
      post '/posts/publish' => 'posts#publish'
      post '/posts/unpublish' => 'posts#unpublish'
      post '/posts/upload_asset' => 'posts#upload_asset'
      post '/posts/destroy_asset' => 'posts#destroy_asset'
      get '/posts/get_posts_count' => 'posts#get_post_count_by_location_with_radius'
      get '/posts/get_post_messages' => 'posts#get_post_messages'
      get '/posts/get_post_message_info' => 'posts#get_post_message_info'
      get '/posts/get_message' => 'posts#get_message'
      
      get '/servicing_agents' => 'servicing_agents#index'
      get '/servicing_agents/info' => 'servicing_agents#info'
      get '/servicing_agents/my_services/:id' => 'servicing_agents#my_services'
      post '/servicing_agents/create' => 'servicing_agents#create'
      post '/servicing_agents/update/:id' => 'servicing_agents#update'
      post '/servicing_agents/destroy/:id' => 'servicing_agents#destroy'
      
      get '/services' => 'services#index'
      get '/services/info/:id' => 'services#info'
      get '/services/my_services/:id' => 'services#my_services'
      post '/services/create' => 'services#create'
      post '/services/update/:id' => 'services#update'
      post '/services/destroy/:id' => 'services#destroy'
      
      get '/search/posts' => 'search#index'
      
      get '/bookmarks' => 'bookmarks#index'
      get '/bookmarks/:user_id' => 'bookmarks#index'
      post '/bookmarks/create' => 'bookmarks#create'
      post '/bookmarks/delete' => 'bookmarks#destroy'
     
      get 'misc/:type' => 'miscellaneous#index'
      
      post 'share/app' => 'share#share_app'
      post 'share/post' => 'share#share_post'
      
      post 'feedback/send' => 'feedback#leave_feedback'
      
      get '/announcements' => 'announcements#index'
      get '/announcements/info/:id' => 'announcements#info'
      
      get 'chat/hello_world' => "chat#hello_world"
      post 'chat/webhooks' => "chat#webhooks"
      post 'chat/auth' => "chat#auth"
      post 'chat/email_message' => "chat#email_message"
      get 'chat/my_messages' => "chat#my_messages"
      get 'chat/message_info/:id' => "chat#message_info"
      post 'chat/delete_message' => "chat#delete_message"
      
      post 'analytics/user/activity' => "analytics#user_activity_log"
      post 'analytics/guest/activity' => "analytics#guest_activity_log"
      
      
      post 'messages/:id/:status' => "messages#updatestatus"
      get 'messages/:user_id/unread' => "messages#get_unread"
      delete 'messages/:id/:type' => "messages#delete_message"
      
      get '/regions' => 'regions#index'
      
      resources :conversations do
        resources :messages
      end 

    end
  end
  
  scope :admin do
    get 'home' => 'home#index'
    get 'home/export_posts/:type/posts' => 'home#export_posts'
    get 'home/export_users/:type/users' => 'home#export_users'
    get 'home/export_post_views' => 'home#export_post_views'
    get 'home/export_shares/:share_type/shared' => 'home#export_shares'
    get 'home/export_feedbacks' => 'home#export_feedbacks'
    
    resources :users, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      post 'block'
      post 'unblock'
      get 'edit_profile'
    end
    
    resources :posts
    resources :admin_posts   
    resources :properties
    resources :property_tenures
    resources :property_types
    resources :property_sizes
    resources :property_psfs
    resources :property_price_ranges
    resources :property_categories
    resources :property_year_constructeds
    
    resources :rooms
    resources :room_share_genders
    resources :lease_terms
    resources :furnishings
    resources :room_categories
    resources :room_bathroom_types

    resources :landmarks
  
    resources :servicing_agents
    
    resources :share_apps, only: [:index, :destroy]
    
    resources :feedbacks, only: [:index, :destroy]
    
    resources :images
    
    resources :announcements
    
    resources :settings
    
    resources :refer_codes
    
    resources :regions
    
    resources :cities
  end
  
  scope :web_account do
    get '/' => 'web_accounts#index'
    get 'credits' => 'web_accounts#index'
    post 'credits' => 'web_accounts#index'
    get 'edit_profile' => 'web_accounts#edit_profile'
    get 'change_password' => 'web_accounts#change_password'
    patch 'update' => 'web_accounts#update'
    patch 'update_password' => 'web_accounts#update_password'
    
    post "credits/hook" => "web_accounts#hook"
    get 'credits/buy' => 'account_credits#index'
    post 'credits/payment' => 'account_credits#payment'
  end
  
  get 'account/terms_conditions' => 'terms_conditions#index'
  get 'post/details/:id' => 'posts#details'
  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  default_scope { order(updated_at: :desc)}
  
  validates_presence_of :title
  validates_presence_of :description
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  respond_to :html

  def index
    @announcements = Announcement.all
    respond_with(@announcements)
  end

  def show
    respond_with(@announcement)
  end

  def new
    @announcement = Announcement.new
    respond_with(@announcement)
  end

  def edit
  end

  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.save
    respond_with(@announcement)
  end

  def update
    @announcement.update(announcement_params)
    respond_with(@announcement)
  end

  def destroy
    @announcement.destroy
    respond_with(@announcement)
  end

  private
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    def announcement_params
      params.require(:announcement).permit(:title, :description)
    end
end

app/controllers/api/v1/announcements_controller.rb
class Api::V1::AnnouncementsController < Api::V1::BaseController
  skip_before_action :authenticate_user_from_token!, only: [:index, :info]
  
  respond_to :json

  def index
    @announcements = Announcement.all
    render :index
  end

  def info
    @announcement = Announcement.find(params[:id])
    render :info
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<div class="well">
<%= form_for @announcement, :html => { :class => "form-horizontal announcement" } do |f| %>

	<% if @announcement.errors.any? %>
	<div id="error_expl" class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title"><%= pluralize(@announcement.errors.count, "error") %> prohibited this task from being saved:</h3>
		</div>
		<div class="panel-body">
			<ul>
				<% @announcement.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
	<% end %>
	
	<div class="control-group">
		<%= f.label :title, :class => 'control-label' %>
		<div class="controls">
			<%= f.text_field :title, :class => 'form-control', required: true, autofocus: true %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :description, :class => 'control-label' %>
		<div class="controls">
			<%= f.text_area :description, :class => 'form-control', required: true %>
		</div>
	</div>
	<br>
	<%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
	<%= link_to t('.cancel', :default => t("helpers.links.cancel")), announcements_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/announcements/edit.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=announcements_path%>">Announcements</a></li>
  <li class="active">Edit</li>
</ol>

<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/announcements/index.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li class="active">Announcements</li>
</ol>

<%- model_class = Announcement -%>
<div class="page-header">
  <h1><i class="fa fa-bullhorn"></i> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= link_to announcement.id, announcement_path(announcement) %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.description %></td>
        <td><%=l announcement.created_at %></td>
        <td>
        	
          <%= link_to content_tag(:span, '', :class => 'fa fa-pencil-square-o', :title => 'Edit'),
                      edit_announcement_path(announcement), :class => 'btn btn-info btn-xs' %>
          <%= link_to content_tag(:span, '', :class => 'fa fa-trash-o', :title => 'Delete'),
                      announcement_path(announcement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_button,
            new_announcement_path,
            :class => 'btn btn-primary' %>

app/views/announcements/new.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=announcements_path%>">Announcements</a></li>
  <li class="active">New</li>
</ol>

<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/announcements/show.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=announcements_path%>">Announcements</a></li>
  <li class="active">Show</li>
</ol>

<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @announcement.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @announcement.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              announcements_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_announcement_path(@announcement), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              announcement_path(@announcement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>