config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_for :users, :path_prefix => 'auth', :skip => [:registrations],
    :controllers => {
        :sessions => "sessions",
    }
    
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      
      devise_for :users, skip: :all
      devise_scope :api_user do
        post '/users/sign_in' => 'sessions#create'
        post '/users/sign_out' => 'sessions#destroy'
        post '/users/sign_up' => 'registrations#create'
      end
      
      get '/users/available_roles' => 'users#available_roles'
      post '/users/update/:id' => 'users#update'
      post '/users/upload_avatar/:id' => 'users#upload_avatar'
      post '/users/change_password/:id' => 'users#change_password'
      post '/users/remove_avatar/:id' => 'users#remove_avatar'
      get '/users/user_info' => 'users#user_info'
            
      get '/posts' => 'posts#index'
      get '/posts/current_user_posts' => 'posts#current_user_posts'
      get '/posts/info' => 'posts#info'
      get '/posts/get_by_location' => 'posts#get_by_location'
      get '/posts/map_posts_listings' => 'posts#map_posts_listings'
      post '/posts/create' => 'posts#create'
      post '/posts/update/:id' => 'posts#update'
      post '/posts/destroy' => 'posts#destroy'
      post '/posts/publish' => 'posts#publish'
      post '/posts/unpublish' => 'posts#unpublish'
      post '/posts/upload_asset' => 'posts#upload_asset'
      post '/posts/destroy_asset' => 'posts#destroy_asset'
      get '/posts/get_posts_count' => 'posts#get_post_count_by_location_with_radius'
      get '/posts/get_post_messages' => 'posts#get_post_messages'
      get '/posts/get_post_message_info' => 'posts#get_post_message_info'
      get '/posts/get_message' => 'posts#get_message'
      
      get '/servicing_agents' => 'servicing_agents#index'
      get '/servicing_agents/info' => 'servicing_agents#info'
      get '/servicing_agents/my_services/:id' => 'servicing_agents#my_services'
      post '/servicing_agents/create' => 'servicing_agents#create'
      post '/servicing_agents/update/:id' => 'servicing_agents#update'
      post '/servicing_agents/destroy/:id' => 'servicing_agents#destroy'
      
      get '/services' => 'services#index'
      get '/services/info/:id' => 'services#info'
      get '/services/my_services/:id' => 'services#my_services'
      post '/services/create' => 'services#create'
      post '/services/update/:id' => 'services#update'
      post '/services/destroy/:id' => 'services#destroy'
      
      get '/search/posts' => 'search#index'
      
      get '/bookmarks' => 'bookmarks#index'
      get '/bookmarks/:user_id' => 'bookmarks#index'
      post '/bookmarks/create' => 'bookmarks#create'
      post '/bookmarks/delete' => 'bookmarks#destroy'
     
      get 'misc/:type' => 'miscellaneous#index'
      
      post 'share/app' => 'share#share_app'
      post 'share/post' => 'share#share_post'
      
      post 'feedback/send' => 'feedback#leave_feedback'
      
      get '/announcements' => 'announcements#index'
      get '/announcements/info/:id' => 'announcements#info'
      
      get 'chat/hello_world' => "chat#hello_world"
      post 'chat/webhooks' => "chat#webhooks"
      post 'chat/auth' => "chat#auth"
      post 'chat/email_message' => "chat#email_message"
      get 'chat/my_messages' => "chat#my_messages"
      get 'chat/message_info/:id' => "chat#message_info"
      post 'chat/delete_message' => "chat#delete_message"
      
      post 'analytics/user/activity' => "analytics#user_activity_log"
      post 'analytics/guest/activity' => "analytics#guest_activity_log"
      
      
      post 'messages/:id/:status' => "messages#updatestatus"
      get 'messages/:user_id/unread' => "messages#get_unread"
      delete 'messages/:id/:type' => "messages#delete_message"
      
      get '/regions' => 'regions#index'
      
      resources :conversations do
        resources :messages
      end 

    end
  end
  
  scope :admin do
    get 'home' => 'home#index'
    get 'home/export_posts/:type/posts' => 'home#export_posts'
    get 'home/export_users/:type/users' => 'home#export_users'
    get 'home/export_post_views' => 'home#export_post_views'
    get 'home/export_shares/:share_type/shared' => 'home#export_shares'
    get 'home/export_feedbacks' => 'home#export_feedbacks'
    
    resources :users, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      post 'block'
      post 'unblock'
      get 'edit_profile'
    end
    
    resources :posts
    resources :admin_posts   
    resources :properties
    resources :property_tenures
    resources :property_types
    resources :property_sizes
    resources :property_psfs
    resources :property_price_ranges
    resources :property_categories
    resources :property_year_constructeds
    
    resources :rooms
    resources :room_share_genders
    resources :lease_terms
    resources :furnishings
    resources :room_categories
    resources :room_bathroom_types

    resources :landmarks
  
    resources :servicing_agents
    
    resources :share_apps, only: [:index, :destroy]
    
    resources :feedbacks, only: [:index, :destroy]
    
    resources :images
    
    resources :announcements
    
    resources :settings
    
    resources :refer_codes
    
    resources :regions
    
    resources :cities
  end
  
  scope :web_account do
    get '/' => 'web_accounts#index'
    get 'credits' => 'web_accounts#index'
    post 'credits' => 'web_accounts#index'
    get 'edit_profile' => 'web_accounts#edit_profile'
    get 'change_password' => 'web_accounts#change_password'
    patch 'update' => 'web_accounts#update'
    patch 'update_password' => 'web_accounts#update_password'
    
    post "credits/hook" => "web_accounts#hook"
    get 'credits/buy' => 'account_credits#index'
    post 'credits/payment' => 'account_credits#payment'
  end
  
  get 'account/terms_conditions' => 'terms_conditions#index'
  get 'post/details/:id' => 'posts#details'
  

end

app/controllers/web_accounts_controller.rb
class WebAccountsController < ApplicationController
  before_action :authenticate_user!, :except => [:hook]
  skip_before_filter :verify_authenticity_token
  
  layout 'web_account'
  def index
    if current_user.account_credit.nil?
      current_user.account_credit = AccountCredit.create(user_id: current_user.id, amount: 0)
    end
    
    @promotion = Setting.find_by_variable('on_promotion')
  end
  
  def edit_profile
    @user = current_user
  end
  
  def change_password
    @user = current_user
  end
  
  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @credit = AccountCredit.find params[:invoice]
      
      total_amount = @credit.amount + params[:mc_gross].to_f
      @credit.update_attributes(amount: total_amount, notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now)
    end
    render nothing: true
  end
  
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    @user = current_user
    if @user.update(user_params)
        redirect_to credits_path  
    else
        render 'web_accounts/edit_profile'  
    end
  end

  def update_password
    @user = current_user
    if @user.update(user_params)
        redirect_to credits_path  
    else
        render 'web_accounts/change_password'  
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :email, :avatar, :delete_avatar, :mobile, :password, :password_confirmation, agent_info_attributes: [:id, :reg_no, :reg_period_start, :reg_period_end, :estate_agent_name, :estate_agent_license_number])
    end
end

app/views/web_accounts/_buy_credit_modal.html.erb
<div class="modal fade" id="buyCreditModal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">Buy Credit</h2>
      </div>
      <div class="modal-body">
        <h3>Unlock even more features with WhatsProp Credit</h3>

		<h5>Pay as you go - add credit and use it when you need it.</h5>  
		<hr>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <a href="<%=credits_buy_path%>" class="btn btn-primary">Add credit to your account</a>
      </div>
    </div>
  </div>
</div>

app/views/web_accounts/change_password.html.erb
<div class="page-header">
  <h1>Change Password</h1>
</div>

<div class="well col-lg-10">
<%= form_for @user, url:update_password_path, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
	
  <div class="control-group">
    <label class="control-label">New Password*</label>
    <div class="controls">
      <%= f.password_field :password, :class => "form-control", :id => "passnew", :placeholder=>"Password", :autocomplete => 'off'  %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Confirm Password*</label>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => "form-control", :id => "passconfirm", :placeholder=>"Confirm Password" %>
    </div>
  </div>
              
  <br>
  <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            credits_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/web_accounts/edit_profile.html.erb
<div class="page-header">
  <h1>Profile</h1>
</div>

<div class="well col-lg-10">
<%= form_for @user, url:update_path, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
	
	<h3>Personal Info</h3>	
	<div class="control-group">
	<label for="avatar" class="control-label">Profile Picture</label>
	<div class="controls">
		<div data-provides="fileupload" class="fileupload fileupload-new">
			<div class="fileupload-new fileupload-small thumbnail">
				<%= @user.avatar.present? ? image_tag(@user.avatar.url(:thumb)) : image_tag("default-avatar.png") %>
			</div>
			<span class="btn btn-default btn-file">
				<%if @user.avatar.present?%>
					<span class="fileupload-new">Change</span>	
				<%else%>
					<span class="fileupload-new">Select image</span>
				<%end%>
				<%= f.file_field :avatar%>
			</span>
		</div>
	</div>
  </div>
  
  
  <div class="control-group">
    <label class="control-label">Username</label>
    <div class="controls">
      <%= f.text_field :username, :class => 'form-control', autofocus: true %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">First Name</label>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'form-control' %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Last Name</label>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'form-control' %>
    </div>
  </div>
  <br>
  
  <h3>Contact details</h3>
  <div class="control-group">
    <label class="control-label">Email*</label>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control', required: true %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Mobile phone</label>
    <div class="controls">
      <%= f.text_field :mobile, :class => "form-control", :placeholder=>"Mobile phone" %>
    </div>
  </div>
<br>

<%unless current_user.agent_info.nil?%>
	<%= f.fields_for :agent_info do |f_agent| %>
		  <h3>Agent Info</h3>
		  <div class="control-group">
		    <label class="control-label">Registration No*</label>
		    <div class="controls">
		      <%= f_agent.text_field :reg_no, :class => 'form-control', required: true %>
		    </div>
		  </div>
		
		<div class="control-group">
			<label class="control-label">Registration Period Start</label>
			<div class="input-group">
				<span class="input-group-addon" id="sizing-addon2"><i class="fa fa-calendar"></i></span>
				<%= f_agent.text_field :reg_period_start, :value => (f_agent.object.reg_period_start.strftime('%d/%m/%Y') if f_agent.object.reg_period_start), required: true, :data => {:provide => "datepicker", "date-format" => "dd/mm/yyyy"}, :class => 'form-control', placeholder: "dd/mm/yyyy"%>
			</div>
		</div>
		
		  <div class="control-group">
		    <label class="control-label">Registration Period End</label>
		    <div class="input-group">
				<span class="input-group-addon" id="sizing-addon2"><i class="fa fa-calendar"></i></span>
				<%= f_agent.text_field :reg_period_end, :value => (f_agent.object.reg_period_end.strftime('%d/%m/%Y') if f_agent.object.reg_period_end), required: true, :data => {:provide => "datepicker", "date-format" => "dd/mm/yyyy"}, :class => 'form-control', placeholder: "dd/mm/yyyy"%>
			</div>
		  </div>
		  
		  <div class="control-group">
		    <label class="control-label">Estate Agent Name</label>
		    <div class="controls">
		      <%= f_agent.text_field :estate_agent_name, :class => "form-control", required: true %>
		    </div>
		  </div>
		  
		  <div class="control-group">
		    <label class="control-label">Estate Agent License Number</label>
		    <div class="controls">
		      <%= f_agent.text_field :estate_agent_license_number, :class => "form-control", required: true %>
		    </div>
		  </div>
		
	<%end%>
	<br>
	<%end%>
	
<!--  
  <br>
  <h3>Change Password</h3>
  <div class="control-group">
    <label class="control-label">Password*</label>
    <div class="controls">
      <%= f.password_field :password, :class => "form-control", :id => "passnew", :placeholder=>"Password", :autocomplete => 'off'  %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Confirm Password*</label>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => "form-control", :id => "passconfirm", :placeholder=>"Confirm Password" %>
    </div>
  </div>
-->              
  <%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            credits_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/web_accounts/index.html.erb
<div class="row-fluid" id="alert-container">
	<%= render partial: 'layouts/alert' %>
</div>
<div class="container text">
	<div class="row">
		<div class="col-sm-12">
			<h1><i class="fa fa-user"></i> My Account</h1>
		</div>
	</div>
</div>
<hr>
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 profile-account">
			<div class="thumbnail">
				<%= current_user.avatar.present? ? image_tag(current_user.avatar.url(:medium)) : image_tag("default-avatar.png") %>
				<div class="caption">
					<hr>
					<!--<h5><span class="badge alert-info"><i class="fa fa-money"></i></span><span> You can add credit in your account</span></h5>
					-->
					<ul class="list-group">
					  <li class="list-group-item" style="<%='height:50px' if @promotion.value == 'yes' %>">
					    <i class="fa fa-money alert-info"></i>
					    <span class="badge alert-success" style="<%='text-decoration: line-through' if @promotion.value == 'yes' %>">
					    	<%=current_user.account_credit.amount%>
					    </span>
					     WhatsProp Credit
					     <% if @promotion.value == 'yes' %>
					     <span class="badge alert-warning" style="margin: 0px -15px 0px 0px;">Promotion</span>
					     <% end %>
					  </li>
					  <li class="list-group-item">
						 <a data-toggle="modal" data-target="#buyCreditModal" class="btn btn-primary btn-block btn-lg">
						 Discover Credit</a>
					  </li>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-9 col-md-8 col-lg-8">
			<h1>Take WhatsProp with you</h1>
			<h4> 
				Whatsprop is an app aimed to assist users in renting of flats and finding rooms to stay with convenience yet at a low cost. 
				Being a consumer to consumer based application, it eliminates the need for agents resulting in cost reduction. 
				With an app providing a platform for property ads solely showing the profiles only (no transactions through the app), 
				you save time and money. Coming to you soon. 
			</h4>

		</div>
		<div class="col-xs-12 col-sm-9 col-md-8 col-lg-8">
			<hr/>
		</div>
		<div class="col-xs-12 col-sm-9 col-md-8 col-lg-8">
			<h1>Account Details</h1>
			<!--<div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
				<h4>Billing and payments</h4>
				<p><a href="#"><i class="fa fa-credit-card"></i> Billing Information</a></p>
				<p><a href="#"><i class="fa fa-eur"></i> Change Currency</a></p>
			</div>-->
			<div class="col-xs-8 col-sm-4 col-md-4 col-lg-4">
				<h4>Settings and preferences</h4>
				<p><a href="<%=edit_profile_path%>"><i class="fa fa-user"></i> Edit Profile</a></p>
				<p><a href="<%=change_password_path%>"><i class="fa fa-key"></i> Change Password</a></p>
			</div>
		</div>
	</div>
</div>

<%= render :partial => 'buy_credit_modal'%>

app/views/web_accounts/profile.html.erb
<div class="row-fluid" id="alert-container">
	<%= render partial: 'layouts/alert' %>
</div>
<div class="container text">
	<div class="row">
		<div class="col-sm-12">
			<h1><i class="fa fa-user"></i> Profile</h1>
		</div>
	</div>
</div>
<hr>
<div class="container-fluid">
	
	<nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
    		<h2>Personal Information</h2>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-5">
          <p class="navbar-text navbar-right"><a class="btn btn-info" href="#">Edit Profile </a></p>
        </div>
      </div>
    </nav>
		
	<div class="well">
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-2">
					<label><h5>Profile Picture</h5></label>
				</div>
				<div class="col-lg-2">
					<%= current_user.avatar.present? ? image_tag(current_user.avatar.url(:medium)) : image_tag("default-avatar.png") %>
				</div>
			</div>
		</div>
		<hr>	
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-2">
					<label><h5>First Name</h5></label>
				</div>
				<div class="col-lg-2">
					<%if current_user.first_name.nil?%>
						<label><h5><a href="#">Add first name</a></h5></label>				
					<%else%>
						<label><h5><strong><%=current_user.first_name%></strong></h5></label>
					<%end%>
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-2">
					<label><h5>Last Name</h5></label>
				</div>
				<div class="col-lg-2">
					<%if current_user.last_name.nil?%>
						<label><h5><a href="#">Add last name</a></h5></label>
					<%else%>
						<label><h5><strong><%=current_user.last_name%></strong></h5></label>
					<%end%>
				</div>
			</div>
		</div>
	</div>
	<br>
	<h3>Contact Details</h3>
	<div class="well">
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-2">
					<label><h5>Email address</h5></label>
				</div>
				<div class="col-lg-2">
					<label><h5><strong><%=current_user.email%></strong></h5></label>
				</div>
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-lg-12">
				<div class="col-lg-2">
					<label><h5>Mobile Phone</h5></label>
				</div>
				<div class="col-lg-2">
					<%if current_user.mobile.nil?%>
						<label><h5><a href="#">Add mobile phone</a></h5></label>
					<%else%>
						<label><h5><strong><%=current_user.mobile%></strong></h5></label>
					<%end%>
					
				</div>
			</div>
		</div>
	</div>
	
</div>