config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_for :users, :path_prefix => 'auth', :skip => [:registrations],
    :controllers => {
        :sessions => "sessions",
    }
    
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      
      devise_for :users, skip: :all
      devise_scope :api_user do
        post '/users/sign_in' => 'sessions#create'
        post '/users/sign_out' => 'sessions#destroy'
        post '/users/sign_up' => 'registrations#create'
      end
      
      get '/users/available_roles' => 'users#available_roles'
      post '/users/update/:id' => 'users#update'
      post '/users/upload_avatar/:id' => 'users#upload_avatar'
      post '/users/change_password/:id' => 'users#change_password'
      post '/users/remove_avatar/:id' => 'users#remove_avatar'
      get '/users/user_info' => 'users#user_info'
            
      get '/posts' => 'posts#index'
      get '/posts/current_user_posts' => 'posts#current_user_posts'
      get '/posts/info' => 'posts#info'
      get '/posts/get_by_location' => 'posts#get_by_location'
      get '/posts/map_posts_listings' => 'posts#map_posts_listings'
      post '/posts/create' => 'posts#create'
      post '/posts/update/:id' => 'posts#update'
      post '/posts/destroy' => 'posts#destroy'
      post '/posts/publish' => 'posts#publish'
      post '/posts/unpublish' => 'posts#unpublish'
      post '/posts/upload_asset' => 'posts#upload_asset'
      post '/posts/destroy_asset' => 'posts#destroy_asset'
      get '/posts/get_posts_count' => 'posts#get_post_count_by_location_with_radius'
      get '/posts/get_post_messages' => 'posts#get_post_messages'
      get '/posts/get_post_message_info' => 'posts#get_post_message_info'
      get '/posts/get_message' => 'posts#get_message'
      
      get '/servicing_agents' => 'servicing_agents#index'
      get '/servicing_agents/info' => 'servicing_agents#info'
      get '/servicing_agents/my_services/:id' => 'servicing_agents#my_services'
      post '/servicing_agents/create' => 'servicing_agents#create'
      post '/servicing_agents/update/:id' => 'servicing_agents#update'
      post '/servicing_agents/destroy/:id' => 'servicing_agents#destroy'
      
      get '/services' => 'services#index'
      get '/services/info/:id' => 'services#info'
      get '/services/my_services/:id' => 'services#my_services'
      post '/services/create' => 'services#create'
      post '/services/update/:id' => 'services#update'
      post '/services/destroy/:id' => 'services#destroy'
      
      get '/search/posts' => 'search#index'
      
      get '/bookmarks' => 'bookmarks#index'
      get '/bookmarks/:user_id' => 'bookmarks#index'
      post '/bookmarks/create' => 'bookmarks#create'
      post '/bookmarks/delete' => 'bookmarks#destroy'
     
      get 'misc/:type' => 'miscellaneous#index'
      
      post 'share/app' => 'share#share_app'
      post 'share/post' => 'share#share_post'
      
      post 'feedback/send' => 'feedback#leave_feedback'
      
      get '/announcements' => 'announcements#index'
      get '/announcements/info/:id' => 'announcements#info'
      
      get 'chat/hello_world' => "chat#hello_world"
      post 'chat/webhooks' => "chat#webhooks"
      post 'chat/auth' => "chat#auth"
      post 'chat/email_message' => "chat#email_message"
      get 'chat/my_messages' => "chat#my_messages"
      get 'chat/message_info/:id' => "chat#message_info"
      post 'chat/delete_message' => "chat#delete_message"
      
      post 'analytics/user/activity' => "analytics#user_activity_log"
      post 'analytics/guest/activity' => "analytics#guest_activity_log"
      
      
      post 'messages/:id/:status' => "messages#updatestatus"
      get 'messages/:user_id/unread' => "messages#get_unread"
      delete 'messages/:id/:type' => "messages#delete_message"
      
      get '/regions' => 'regions#index'
      
      resources :conversations do
        resources :messages
      end 

    end
  end
  
  scope :admin do
    get 'home' => 'home#index'
    get 'home/export_posts/:type/posts' => 'home#export_posts'
    get 'home/export_users/:type/users' => 'home#export_users'
    get 'home/export_post_views' => 'home#export_post_views'
    get 'home/export_shares/:share_type/shared' => 'home#export_shares'
    get 'home/export_feedbacks' => 'home#export_feedbacks'
    
    resources :users, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      post 'block'
      post 'unblock'
      get 'edit_profile'
    end
    
    resources :posts
    resources :admin_posts   
    resources :properties
    resources :property_tenures
    resources :property_types
    resources :property_sizes
    resources :property_psfs
    resources :property_price_ranges
    resources :property_categories
    resources :property_year_constructeds
    
    resources :rooms
    resources :room_share_genders
    resources :lease_terms
    resources :furnishings
    resources :room_categories
    resources :room_bathroom_types

    resources :landmarks
  
    resources :servicing_agents
    
    resources :share_apps, only: [:index, :destroy]
    
    resources :feedbacks, only: [:index, :destroy]
    
    resources :images
    
    resources :announcements
    
    resources :settings
    
    resources :refer_codes
    
    resources :regions
    
    resources :cities
  end
  
  scope :web_account do
    get '/' => 'web_accounts#index'
    get 'credits' => 'web_accounts#index'
    post 'credits' => 'web_accounts#index'
    get 'edit_profile' => 'web_accounts#edit_profile'
    get 'change_password' => 'web_accounts#change_password'
    patch 'update' => 'web_accounts#update'
    patch 'update_password' => 'web_accounts#update_password'
    
    post "credits/hook" => "web_accounts#hook"
    get 'credits/buy' => 'account_credits#index'
    post 'credits/payment' => 'account_credits#payment'
  end
  
  get 'account/terms_conditions' => 'terms_conditions#index'
  get 'post/details/:id' => 'posts#details'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
  def dashboard
  end
  
  def export_posts
    if params[:type] == 'range'
      @posts = Post.where(created_at: 3.month.ago..Time.now)
      
      data = CSV.generate do |csv|
        @posts.each_with_index do |post, index|  
          if (index == 0)
            csv << ["Title", "Description", "Status", "Posted By", "Category", "Price", "Location", "Posted On"]  
          end
          if post.room.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Room for "+ post.room.room_category.name, post.room.price, post.room.location.address, post.created_at.strftime("%B %d, %Y")]
          elsif post.property.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Property for "+ post.property.property_category.name, post.property.price, post.property.location.address, post.created_at.strftime("%B %d, %Y")]
          end
        end 
      end
  
    elsif params[:type] == 'all'
      data = CSV.generate do |csv|
        csv << ["Title", "Description", "Status", "Posted By", "Category", "Price", "Location", "Posted On"] 
        
        @active = Post.active
        @active.each_with_index do |post, index|  
          if post.room.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Room for "+ post.room.room_category.name, post.room.price, post.room.location.address, post.created_at.strftime("%B %d, %Y")]
          elsif post.property.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Property for "+ post.property.property_category.name, post.property.price, post.property.location.address, post.created_at.strftime("%B %d, %Y")]
          end
        end
        
        csv << []        
        @inactive = Post.inactive
        @inactive.each_with_index do |post, index|  
          if post.room.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Room for "+ post.room.room_category.name, post.room.price, post.room.location.address, post.created_at.strftime("%B %d, %Y")]
          elsif post.property.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Property for "+ post.property.property_category.name, post.property.price, post.property.location.address, post.created_at.strftime("%B %d, %Y")]
          end
        end
        csv << []
        @draft = Post.draft
        @draft.each_with_index do |post, index|  
          if post.room.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Room for "+ post.room.room_category.name, post.room.price, post.room.location.address, post.created_at.strftime("%B %d, %Y")]
          elsif post.property.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Property for "+ post.property.property_category.name, post.property.price, post.property.location.address, post.created_at.strftime("%B %d, %Y")]
          end
        end
        
        csv << []
        @expired = Post.expired
        @expired.each_with_index do |post, index|  
          if post.room.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Room for "+ post.room.room_category.name, post.room.price, post.room.location.address, post.created_at.strftime("%B %d, %Y")]
          elsif post.property.present?
            csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, post.user.email, "Property for "+ post.property.property_category.name, post.property.price, post.property.location.address, post.created_at.strftime("%B %d, %Y")]
          end
        end
         
      end
      
    end
    
    respond_to do |format|
        format.csv { send_data data, filename: 'Posts.csv' }
    end
  end
  
  def export_post_views
    @post_views = PostView.all
    data = CSV.generate do |csv|
      csv << ["Post Title", "Post Description", "Post Status", "Category", "Viewed By", "Viewed On"]
      @post_views.each do |post_view|  
        post = post_view.post
        viewed_by = post_view.user.nil? ? "Guest" : post_view.user.email
        if post.room.present?
          csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, "Room for "+ post.room.room_category.name, viewed_by, post_view.created_at.strftime("%B %d, %Y")]
        elsif post.property.present?
          csv << [post.title.html_safe, post.description.html_safe, post.status.upcase!, "Property for "+ post.property.property_category.name, viewed_by, post_view.created_at.strftime("%B %d, %Y")]
        end
      end 
    end
      
    respond_to do |format|
        format.csv { send_data data, filename: 'PostViews.csv' }
    end
  end
  
  def export_users
    if params[:type] == 'all'
      @users = User.all
      data = CSV.generate do |csv|
        csv << ["Email", "Firstname", "Lastname", "Username", "Mobile", "Role", "Date Registered"]
        @users.each do |user|  
          csv << [user.email, user.first_name, user.last_name, user.username, user.mobile, user.user_role.name, user.created_at.strftime("%B %d, %Y")]
        end 
      end
    elsif params[:type] == 'range'
      @users = User.where(created_at: 1.month.ago..Time.now)
      data = CSV.generate do |csv|
        csv << ["Email", "Firstname", "Lastname", "Username", "Mobile", "Role", "Date Registered"]
        @users.each do |user|  
          csv << [user.email, user.first_name, user.last_name, user.username, user.mobile, user.user_role.name, user.created_at.strftime("%B %d, %Y")]
        end 
      end
    else
      if params[:type] == 'avg'
        @user_activity_logs = UserActivityLog.all  
        data = CSV.generate do |csv|
          csv << ["User", "Dwell Time (ms)"]
          @user_activity_logs.each do |activity|  
            csv << [activity.user.email, activity.dwell_time + " ms"]
          end 
        end
      
      elsif params[:type] == 'unique'
        @guest_activity_logs = GuestActivityLog.all  
        data = CSV.generate do |csv|
          csv << ["Action", "Created At"]
          @guest_activity_logs.each do |activity|  
            csv << [activity.action, activity.created_at.strftime("%B %d, %Y %H:%M:%S %p")]
          end 
        end
      end   
    end
    
    respond_to do |format|
        format.csv { send_data data, filename: 'Users.csv' }
    end
  end
  
  def export_shares
    if params[:share_type] == 'posts'
      fname = 'PostsShared.csv'
      @post_shares = PostShare.all
      data = CSV.generate do |csv|
        csv << ["Post Title", "Shared By", "Email", "Share Type", "Created At"]
        @post_shares.each do |share|  
          csv << [share.post.title, share.user.email, share.email, share.share_type, share.created_at.strftime("%B %d, %Y %H:%M:%S %p")]
        end 
      end
      
    elsif params[:share_type] == 'apps'
      fname = 'AppsShared.csv'
      @app_shares = AppShare.all  
      data = CSV.generate do |csv|
        csv << ["Shared By", "Email", "Share Type", "Created At"]
        @app_shares.each do |share|  
          csv << [share.user.email, share.email, share.share_type, share.created_at.strftime("%B %d, %Y %H:%M:%S %p")]
        end 
      end
    end
    
    respond_to do |format|
        format.csv { send_data data, filename: fname }
    end
  end
  
  def export_feedbacks
    @feedbacks = Feedback.all
    data = CSV.generate do |csv|
        csv << ["Feedback From", "Message", "Created At"]
        @feedbacks.each do |fb|  
          csv << [fb.user.email, fb.message, fb.created_at.strftime("%B %d, %Y %H:%M:%S %p")]
        end 
      end
      
    respond_to do |format|
        format.csv { send_data data, filename: "Feedbacks.csv" }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class="row-fluid" id="alert-container">
	<%= render partial: 'layouts/alert' %>
</div>

app/views/home/index.html.erb
<div class="row-fluid" id="alert-container">
	<%= render partial: 'layouts/alert' %>
</div>
<div class="page-header">
	<h1><i class="fa fa-dashboard"></i> Dashboard</h1>
</div>

<div class="row box box-transparent">
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link blue-background">
			<a href="<%= posts_path%>">
			<div class="header">
				<div class="fa fa-check-square-o"></div>
			</div>
			<div class="content">
				Posts
			</div> </a>
		</div>
	</div>
	
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link orange-background">
			<a href="<%= users_path%>">
			<div class="header">
				<div class="fa fa-users"></div>
			</div>
			<div class="content">
				Registered Users
			</div> </a>
		</div>
	</div>
	
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link purple-background">
			<a href="<%= servicing_agents_path%>">
			<div class="header">
				<div class="fa fa-user"></div>
			</div>
			<div class="content">
				Servicing Agents
			</div> </a>
		</div>
	</div>
	
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link green-background">
			<a href="<%= share_apps_path%>">
			<div class="header">
				<div class="fa fa-share-alt"></div>
			</div>
			<div class="content">
				Share Apps
			</div> </a>
		</div>
	</div>
	
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link red-background">
			<a href="<%= feedbacks_path%>">
			<div class="header">
				<div class="fa fa-comments"></div>
			</div>
			<div class="content">
				Feedbacks
			</div> </a>
		</div>
	</div>
	
	<div class="col-xs-4 col-sm-2">
		<div class="box-quick-link banana-background">
			<a href="<%= announcements_path%>">
			<div class="header">
				<div class="fa fa-bullhorn"></div>
			</div>
			<div class="content">
				Announcements
			</div> </a>
		</div>
	</div>
</div>
<!--
<div class="row">
	<div class="col-sm-6">
		<div class="well">
			<h4>Posts in the last three months</h4>
			<%= column_chart Post.group_by_week(:created_at, format: '%b %d %Y').count, colors: ["#468847", "#f8a326", "#b94a48", "#9564e2"],  library: {backgroundColor: "#f5f5f5"} %>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="well">
			<h4>New registered users in the last month</h4>
			<%= line_chart User.where(created_at: 1.month.ago..Time.now).group_by_week(:created_at).count, library: {backgroundColor: "#f5f5f5"} %>
		</div>
	</div>
</div>
-->
<div class="row">
	<div class="col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<div class="fa fa-check-square-o"></div>
					Posts in the last three months
				</div>
				<div class="actions">
					<div class="btn-group">
					  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					    <i class="fa fa-rocket"></i> Export <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="/admin/home/export_posts/range/posts.csv">Recent Posts</a></li>
					    <li class="divider"></li>
					    <li><a href="/admin/home/export_posts/all/posts.csv">All Posts</a></li>
					  </ul>
					</div>
					
				</div>
			</div>
			<div class="well">
				<%= column_chart Post.group_by_week(:created_at, format: '%b %d %Y').count, colors: ["#00acec"],  library: {backgroundColor: "#f5f5f5"} %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<div class="fa fa-users"></div>
					Registered users in the last month
				</div>
				<div class="actions">
					<div class="btn-group">
					  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					    <i class="fa fa-rocket"></i> Export <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="/admin/home/export_users/range/users.csv">Recent Users</a></li>
					    <li class="divider"></li>
					    <li><a href="/admin/home/export_users/all/users.csv">All Users</a></li>
					  </ul>
					</div>
				</div>	
			</div>
			<div class="well">
				<%= line_chart User.where(created_at: 1.month.ago..Time.now).group_by_week(:created_at).count, colors: ["#f8a326"], library: {backgroundColor: "#f5f5f5"} %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-6 col-md-3">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<div class="fa fa-check-square-o"></div>
					Posts
				</div>
				<div class="actions"><a href="/admin/home/export_posts/all/posts.csv" class="btn btn-default"><i class="fa fa-rocket"></i> Export</a></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="box-content box-statistic">
						<h3 class="title text-warning"><%= Post.draft.count%></h3>
						<small>Draft</small>
						<div class="text-warning fa fa-inbox align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-success"><%= Post.active.count%></h3>
						<small>Active</small>
						<div class="text-success fa fa-check-square-o align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-purple"><%= Post.inactive.count%></h3>
						<small>Inactive</small>
						<div class="text-purple fa fa-archive align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-red"><%= Post.expired.count%></h3>
						<small>Expired</small>
						<div class="text-red fa fa-clock-o align-right"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-3">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<i class="fa fa-group"></i>
					Visitors
				</div>
				<div class="actions">
					<div class="btn-group">
					  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					    <i class="fa fa-rocket"></i> Export <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="/admin/home/export_users/unique/users.csv">Unique Guests</a></li>
					    <li class="divider"></li>
					    <li><a href="/admin/home/export_post_views.csv">Post Views</a></li>
					    <li class="divider"></li>
					    <li><a href="/admin/home/export_users/avg/users.csv">User Average Time</a></li>
					  </ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="box-content box-statistic">
						<h3 class="title text-error"><%=GuestActivityLog.count%></h3>
						<small>Unique</small>
						<div class="text-error fa fa-user align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-warning"><%=PostView.count%></h3>
						<small>Post views</small>
						<div class="text-warning fa fa-book align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-primary"><%=UserActivityLog.avg_to_hour%></h3>
						<small>Average time</small>
						<div class="text-primary fa fa-clock-o align-right"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-3">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<i class="fa fa-share-alt-square"></i>
					Shares
				</div>
				<div class="actions">
					<div class="btn-group">
						  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
						    <i class="fa fa-rocket"></i> Export <span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" role="menu">
						    <li><a href="/admin/home/export_shares/apps/shared.csv">Apps Shared</a></li>
						    <li class="divider"></li>
						    <li><a href="/admin/home/export_shares/posts/shared.csv">Posts Shared</a></li>
						  </ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="box-content box-statistic">
						<h3 class="title text-error"><%= PostShare.count %></h3>
						<small>Posts Shared</small>
						<div class="text-error fa fa-share-square-o align-right"></div>
					</div>
					<div class="box-content box-statistic">
						<h3 class="title text-success"><%= AppShare.count %></h3>
						<small>Apps Shared</small>
						<div class="text-success fa fa-rocket align-right"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-3">
		<div class="box">
			<div class="box-header">
				<div class="title">
					<i class="fa fa-comments"></i>
					Feedbacks
				</div>
				<div class="actions"><a href="/admin/home/export_feedbacks.csv" class="btn btn-default"><i class="fa fa-rocket"></i> Export</a></div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="box-content box-statistic">
						<h3 class="title text-info"><%= Feedback.count %></h3>
						<small>Feedbacks</small>
						<div class="text-info fa fa-comments-o align-right"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>