config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  devise_for :users, :path_prefix => 'auth', :skip => [:registrations],
    :controllers => {
        :sessions => "sessions",
    }
    
  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      
      devise_for :users, skip: :all
      devise_scope :api_user do
        post '/users/sign_in' => 'sessions#create'
        post '/users/sign_out' => 'sessions#destroy'
        post '/users/sign_up' => 'registrations#create'
      end
      
      get '/users/available_roles' => 'users#available_roles'
      post '/users/update/:id' => 'users#update'
      post '/users/upload_avatar/:id' => 'users#upload_avatar'
      post '/users/change_password/:id' => 'users#change_password'
      post '/users/remove_avatar/:id' => 'users#remove_avatar'
      get '/users/user_info' => 'users#user_info'
            
      get '/posts' => 'posts#index'
      get '/posts/current_user_posts' => 'posts#current_user_posts'
      get '/posts/info' => 'posts#info'
      get '/posts/get_by_location' => 'posts#get_by_location'
      get '/posts/map_posts_listings' => 'posts#map_posts_listings'
      post '/posts/create' => 'posts#create'
      post '/posts/update/:id' => 'posts#update'
      post '/posts/destroy' => 'posts#destroy'
      post '/posts/publish' => 'posts#publish'
      post '/posts/unpublish' => 'posts#unpublish'
      post '/posts/upload_asset' => 'posts#upload_asset'
      post '/posts/destroy_asset' => 'posts#destroy_asset'
      get '/posts/get_posts_count' => 'posts#get_post_count_by_location_with_radius'
      get '/posts/get_post_messages' => 'posts#get_post_messages'
      get '/posts/get_post_message_info' => 'posts#get_post_message_info'
      get '/posts/get_message' => 'posts#get_message'
      
      get '/servicing_agents' => 'servicing_agents#index'
      get '/servicing_agents/info' => 'servicing_agents#info'
      get '/servicing_agents/my_services/:id' => 'servicing_agents#my_services'
      post '/servicing_agents/create' => 'servicing_agents#create'
      post '/servicing_agents/update/:id' => 'servicing_agents#update'
      post '/servicing_agents/destroy/:id' => 'servicing_agents#destroy'
      
      get '/services' => 'services#index'
      get '/services/info/:id' => 'services#info'
      get '/services/my_services/:id' => 'services#my_services'
      post '/services/create' => 'services#create'
      post '/services/update/:id' => 'services#update'
      post '/services/destroy/:id' => 'services#destroy'
      
      get '/search/posts' => 'search#index'
      
      get '/bookmarks' => 'bookmarks#index'
      get '/bookmarks/:user_id' => 'bookmarks#index'
      post '/bookmarks/create' => 'bookmarks#create'
      post '/bookmarks/delete' => 'bookmarks#destroy'
     
      get 'misc/:type' => 'miscellaneous#index'
      
      post 'share/app' => 'share#share_app'
      post 'share/post' => 'share#share_post'
      
      post 'feedback/send' => 'feedback#leave_feedback'
      
      get '/announcements' => 'announcements#index'
      get '/announcements/info/:id' => 'announcements#info'
      
      get 'chat/hello_world' => "chat#hello_world"
      post 'chat/webhooks' => "chat#webhooks"
      post 'chat/auth' => "chat#auth"
      post 'chat/email_message' => "chat#email_message"
      get 'chat/my_messages' => "chat#my_messages"
      get 'chat/message_info/:id' => "chat#message_info"
      post 'chat/delete_message' => "chat#delete_message"
      
      post 'analytics/user/activity' => "analytics#user_activity_log"
      post 'analytics/guest/activity' => "analytics#guest_activity_log"
      
      
      post 'messages/:id/:status' => "messages#updatestatus"
      get 'messages/:user_id/unread' => "messages#get_unread"
      delete 'messages/:id/:type' => "messages#delete_message"
      
      get '/regions' => 'regions#index'
      
      resources :conversations do
        resources :messages
      end 

    end
  end
  
  scope :admin do
    get 'home' => 'home#index'
    get 'home/export_posts/:type/posts' => 'home#export_posts'
    get 'home/export_users/:type/users' => 'home#export_users'
    get 'home/export_post_views' => 'home#export_post_views'
    get 'home/export_shares/:share_type/shared' => 'home#export_shares'
    get 'home/export_feedbacks' => 'home#export_feedbacks'
    
    resources :users, only: [:index, :new, :edit, :show, :create, :update, :destroy] do
      post 'block'
      post 'unblock'
      get 'edit_profile'
    end
    
    resources :posts
    resources :admin_posts   
    resources :properties
    resources :property_tenures
    resources :property_types
    resources :property_sizes
    resources :property_psfs
    resources :property_price_ranges
    resources :property_categories
    resources :property_year_constructeds
    
    resources :rooms
    resources :room_share_genders
    resources :lease_terms
    resources :furnishings
    resources :room_categories
    resources :room_bathroom_types

    resources :landmarks
  
    resources :servicing_agents
    
    resources :share_apps, only: [:index, :destroy]
    
    resources :feedbacks, only: [:index, :destroy]
    
    resources :images
    
    resources :announcements
    
    resources :settings
    
    resources :refer_codes
    
    resources :regions
    
    resources :cities
  end
  
  scope :web_account do
    get '/' => 'web_accounts#index'
    get 'credits' => 'web_accounts#index'
    post 'credits' => 'web_accounts#index'
    get 'edit_profile' => 'web_accounts#edit_profile'
    get 'change_password' => 'web_accounts#change_password'
    patch 'update' => 'web_accounts#update'
    patch 'update_password' => 'web_accounts#update_password'
    
    post "credits/hook" => "web_accounts#hook"
    get 'credits/buy' => 'account_credits#index'
    post 'credits/payment' => 'account_credits#payment'
  end
  
  get 'account/terms_conditions' => 'terms_conditions#index'
  get 'post/details/:id' => 'posts#details'
  

end

app/models/servicing_agent.rb
class ServicingAgent < ActiveRecord::Base
  belongs_to :user
  
  validates_presence_of :title
  validates_presence_of :description
  
  scope :all_with_filter, ->(sort_date, sort_price){
    if !sort_date.blank?
      self.all.order(updated_at: sort_date.to_sym)
    elsif !sort_price.blank?
      self.all.order(price: sort_price.to_sym)
    else
      self.all.order(title: :asc)
    end    
  }
  
  scope :my_services, ->(id, sort_date, sort_price){
    service = self.where(user_id: id)
    if !sort_date.blank?
      service.order(updated_at: sort_date.to_sym)
    elsif !sort_price.blank?
      service.order(price: sort_price.to_sym)
    else
      service.order(created_at: :desc)
    end    
  }
end

app/controllers/api/v1/servicing_agents_controller.rb
class Api::V1::ServicingAgentsController < Api::V1::BaseController
  before_action :set_servicing_agent, only: [:update, :destroy]

  skip_before_action :authenticate_user_from_token!, only: [:index, :info]
  
  respond_to :json

  def index
    @servicing_agents = ServicingAgent.all_with_filter(params[:sort_date], params[:sort_price]).paginate(:page => params[:page], :per_page => params[:item_per_page])
    render :index
  end
  
  def my_services
    @servicing_agents = ServicingAgent.my_services(params[:id], params[:sort_date], params[:sort_price]).paginate(:page => params[:page], :per_page => params[:item_per_page])
    render :index
  end

  def info
    @servicing_agent = ServicingAgent.find(params[:id])
    render :info
  end
  
  def create
    @servicing_agent = ServicingAgent.new(servicing_agent_params)
    if @servicing_agent.save
      render :info
    else
      render status:422, json: { result:false, code:422, errors: @servicing_agent.errors, data:{} }    
    end
  end

  def update
    if @servicing_agent.update(servicing_agent_params)
      render :info
    else
      render status:422, json: { result:false, code:422, errors: @servicing_agent.errors, data:{} }  
    end
  end

  def destroy
    if @servicing_agent.destroy
      render json: { result:true, code:200, errors: {}, data:{}, message: "Success" }
    else
      render status:422, json: { result:false, code:422, errors: @servicing_agent.errors, data:{} }    
    end
    
  end

  private
    def set_servicing_agent
      @servicing_agent = ServicingAgent.find(params[:id])
    end

    def servicing_agent_params
      params.require(:servicing_agent).permit(:title, :description, :price, :user_id)
    end
end

app/controllers/servicing_agents_controller.rb
class ServicingAgentsController < ApplicationController
  before_action :set_servicing_agent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @servicing_agents = ServicingAgent.all
    respond_with(@servicing_agents)
  end

  def show
    respond_with(@servicing_agent)
  end

  def new
    @servicing_agent = ServicingAgent.new
    respond_with(@servicing_agent)
  end

  def edit
  end

  def create
    @servicing_agent = ServicingAgent.new(servicing_agent_params)
    @servicing_agent.save
    respond_with(@servicing_agent)
  end

  def update
    @servicing_agent.update(servicing_agent_params)
    respond_with(@servicing_agent)
  end

  def destroy
    @servicing_agent.destroy
    respond_with(@servicing_agent)
  end

  private
    def set_servicing_agent
      @servicing_agent = ServicingAgent.find(params[:id])
    end

    def servicing_agent_params
      params.require(:servicing_agent).permit(:title, :description, :price, :user_id)
    end
end

app/helpers/servicing_agents_helper.rb
module ServicingAgentsHelper
end

app/views/servicing_agents/_form.html.erb
<div class="well">
<%= form_for @servicing_agent, :html => { :class => "form-horizontal servicing_agent" } do |f| %>

<% if @servicing_agent.errors.any? %>
<div id="error_expl" class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title"><%= pluralize(@servicing_agent.errors.count, "error") %> prohibited this task from being saved:</h3>
	</div>
	<div class="panel-body">
		<ul>
			<% @servicing_agent.errors.full_messages.each do |msg| %>
			<li>
				<%= msg %>
			</li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>

<div class="control-group">
	<%= f.label :title, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :title, :class => 'form-control', required: true, autofocus: true %>
	</div>
	<%= error_span(@servicing_agent[:title]) %>
</div>
<div class="control-group">
	<%= f.label :description, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :description, :class => 'form-control' %>
	</div>
	<%= error_span(@servicing_agent[:description]) %>
</div>
<div class="control-group">
	<%= f.label :price, :class => 'control-label' %>
	<div class="controls">
		<%= f.text_field :price, :class => 'form-control' %>
	</div>
	<%= error_span(@servicing_agent[:price]) %>
</div>
<div class="control-group">
    <label class="control-label">Created By*</label>
    <div class="controls">
      <%= f.select(:user_id, options_for_select(User.all.collect{ |u| [(u.fullname),u.id] }, @servicing_agent.user_id), {}, {multiple: false, class: 'form-control'}) %>
    </div>
  </div>

<br>
<%= f.submit 'Save Changes', :class => 'btn btn-primary' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
servicing_agents_path, :class => 'btn btn-default' %>

<% end %>
</div>

app/views/servicing_agents/edit.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=servicing_agents_path%>">Servicing Agents</a></li>
  <li class="active">Edit</li>
</ol>

<%- model_class = ServicingAgent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicing_agents/index.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li class="active">Servicing Agents</li>
</ol>

<%- model_class = ServicingAgent -%>
<div class="page-header">
  <h1><i class="fa fa-user"></i> <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @servicing_agents.each do |servicing_agent| %>
      <tr>
        <td><%= link_to servicing_agent.id, servicing_agent_path(servicing_agent) %></td>
        <td><%= servicing_agent.title %></td>
        <td><%= servicing_agent.description.truncate(50) unless servicing_agent.description.nil?%></td>
        <td><%= servicing_agent.price %></td>
        <td><%= servicing_agent.user.email %></td>
        <td><%=l servicing_agent.created_at %></td>
        <td>
          
          <%= link_to content_tag(:span, '', :class => 'fa fa-pencil-square-o', :title => 'Edit'),
                      edit_servicing_agent_path(servicing_agent), :class => 'btn btn-info btn-xs' %>
          <%= link_to content_tag(:span, '', :class => 'fa fa-trash-o', :title => 'Delete'),
                      servicing_agent_path(servicing_agent),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_button,
            new_servicing_agent_path,
            :class => 'btn btn-primary' %>

app/views/servicing_agents/new.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=servicing_agents_path%>">Servicing Agents</a></li>
  <li class="active">New</li>
</ol>

<%- model_class = ServicingAgent -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicing_agents/show.html.erb
<ol class="breadcrumb">
  <li><a href="<%= home_path%>">Home</a></li>
  <li><a href="#">Administration</a></li>
  <li><a href="<%=servicing_agents_path%>">Servicing Agents</a></li>
  <li class="active">Show</li>
</ol>

<%- model_class = ServicingAgent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @servicing_agent.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @servicing_agent.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @servicing_agent.price %></dd>
  <dt><strong>Created By:</strong></dt>
  <dd><%= @servicing_agent.user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              servicing_agents_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_servicing_agent_path(@servicing_agent), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              servicing_agent_path(@servicing_agent),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>